id: P48BD8BE9
initial_creation_type: input
source_metadata:
  title: Saṃvitsiddhi
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Somadeva Vasudeva
  contribution to GRETIL: Somadeva Vasudeva
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:58:02.668236'
last_modified_at: '2022-03-09T14:58:02.668249'
